// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/item"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ItemCreate is the builder for creating a Item entity.
type ItemCreate struct {
	config
	mutation *ItemMutation
	hooks    []Hook
}

// SetHash sets the "hash" field.
func (ic *ItemCreate) SetHash(s string) *ItemCreate {
	ic.mutation.SetHash(s)
	return ic
}

// SetTitle sets the "title" field.
func (ic *ItemCreate) SetTitle(s string) *ItemCreate {
	ic.mutation.SetTitle(s)
	return ic
}

// SetDt sets the "dt" field.
func (ic *ItemCreate) SetDt(s string) *ItemCreate {
	ic.mutation.SetDt(s)
	return ic
}

// SetCat sets the "cat" field.
func (ic *ItemCreate) SetCat(s string) *ItemCreate {
	ic.mutation.SetCat(s)
	return ic
}

// SetSize sets the "size" field.
func (ic *ItemCreate) SetSize(i int) *ItemCreate {
	ic.mutation.SetSize(i)
	return ic
}

// SetExtID sets the "ext_id" field.
func (ic *ItemCreate) SetExtID(s string) *ItemCreate {
	ic.mutation.SetExtID(s)
	return ic
}

// SetNillableExtID sets the "ext_id" field if the given value is not nil.
func (ic *ItemCreate) SetNillableExtID(s *string) *ItemCreate {
	if s != nil {
		ic.SetExtID(*s)
	}
	return ic
}

// SetImdb sets the "imdb" field.
func (ic *ItemCreate) SetImdb(s string) *ItemCreate {
	ic.mutation.SetImdb(s)
	return ic
}

// SetNillableImdb sets the "imdb" field if the given value is not nil.
func (ic *ItemCreate) SetNillableImdb(s *string) *ItemCreate {
	if s != nil {
		ic.SetImdb(*s)
	}
	return ic
}

// SetID sets the "id" field.
func (ic *ItemCreate) SetID(i int) *ItemCreate {
	ic.mutation.SetID(i)
	return ic
}

// Mutation returns the ItemMutation object of the builder.
func (ic *ItemCreate) Mutation() *ItemMutation {
	return ic.mutation
}

// Save creates the Item in the database.
func (ic *ItemCreate) Save(ctx context.Context) (*Item, error) {
	return withHooks(ctx, ic.sqlSave, ic.mutation, ic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ic *ItemCreate) SaveX(ctx context.Context) *Item {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ic *ItemCreate) Exec(ctx context.Context) error {
	_, err := ic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ic *ItemCreate) ExecX(ctx context.Context) {
	if err := ic.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ic *ItemCreate) check() error {
	if _, ok := ic.mutation.Hash(); !ok {
		return &ValidationError{Name: "hash", err: errors.New(`ent: missing required field "Item.hash"`)}
	}
	if _, ok := ic.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Item.title"`)}
	}
	if _, ok := ic.mutation.Dt(); !ok {
		return &ValidationError{Name: "dt", err: errors.New(`ent: missing required field "Item.dt"`)}
	}
	if _, ok := ic.mutation.Cat(); !ok {
		return &ValidationError{Name: "cat", err: errors.New(`ent: missing required field "Item.cat"`)}
	}
	if _, ok := ic.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "Item.size"`)}
	}
	return nil
}

func (ic *ItemCreate) sqlSave(ctx context.Context) (*Item, error) {
	if err := ic.check(); err != nil {
		return nil, err
	}
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	ic.mutation.id = &_node.ID
	ic.mutation.done = true
	return _node, nil
}

func (ic *ItemCreate) createSpec() (*Item, *sqlgraph.CreateSpec) {
	var (
		_node = &Item{config: ic.config}
		_spec = sqlgraph.NewCreateSpec(item.Table, sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt))
	)
	if id, ok := ic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ic.mutation.Hash(); ok {
		_spec.SetField(item.FieldHash, field.TypeString, value)
		_node.Hash = value
	}
	if value, ok := ic.mutation.Title(); ok {
		_spec.SetField(item.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := ic.mutation.Dt(); ok {
		_spec.SetField(item.FieldDt, field.TypeString, value)
		_node.Dt = value
	}
	if value, ok := ic.mutation.Cat(); ok {
		_spec.SetField(item.FieldCat, field.TypeString, value)
		_node.Cat = value
	}
	if value, ok := ic.mutation.Size(); ok {
		_spec.SetField(item.FieldSize, field.TypeInt, value)
		_node.Size = value
	}
	if value, ok := ic.mutation.ExtID(); ok {
		_spec.SetField(item.FieldExtID, field.TypeString, value)
		_node.ExtID = value
	}
	if value, ok := ic.mutation.Imdb(); ok {
		_spec.SetField(item.FieldImdb, field.TypeString, value)
		_node.Imdb = value
	}
	return _node, _spec
}

// ItemCreateBulk is the builder for creating many Item entities in bulk.
type ItemCreateBulk struct {
	config
	err      error
	builders []*ItemCreate
}

// Save creates the Item entities in the database.
func (icb *ItemCreateBulk) Save(ctx context.Context) ([]*Item, error) {
	if icb.err != nil {
		return nil, icb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Item, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *ItemCreateBulk) SaveX(ctx context.Context) []*Item {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (icb *ItemCreateBulk) Exec(ctx context.Context) error {
	_, err := icb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icb *ItemCreateBulk) ExecX(ctx context.Context) {
	if err := icb.Exec(ctx); err != nil {
		panic(err)
	}
}
