// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/item"
	"entdemo/ent/predicate"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ItemUpdate is the builder for updating Item entities.
type ItemUpdate struct {
	config
	hooks    []Hook
	mutation *ItemMutation
}

// Where appends a list predicates to the ItemUpdate builder.
func (iu *ItemUpdate) Where(ps ...predicate.Item) *ItemUpdate {
	iu.mutation.Where(ps...)
	return iu
}

// SetHash sets the "hash" field.
func (iu *ItemUpdate) SetHash(s string) *ItemUpdate {
	iu.mutation.SetHash(s)
	return iu
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (iu *ItemUpdate) SetNillableHash(s *string) *ItemUpdate {
	if s != nil {
		iu.SetHash(*s)
	}
	return iu
}

// SetTitle sets the "title" field.
func (iu *ItemUpdate) SetTitle(s string) *ItemUpdate {
	iu.mutation.SetTitle(s)
	return iu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (iu *ItemUpdate) SetNillableTitle(s *string) *ItemUpdate {
	if s != nil {
		iu.SetTitle(*s)
	}
	return iu
}

// SetDt sets the "dt" field.
func (iu *ItemUpdate) SetDt(s string) *ItemUpdate {
	iu.mutation.SetDt(s)
	return iu
}

// SetNillableDt sets the "dt" field if the given value is not nil.
func (iu *ItemUpdate) SetNillableDt(s *string) *ItemUpdate {
	if s != nil {
		iu.SetDt(*s)
	}
	return iu
}

// SetCat sets the "cat" field.
func (iu *ItemUpdate) SetCat(s string) *ItemUpdate {
	iu.mutation.SetCat(s)
	return iu
}

// SetNillableCat sets the "cat" field if the given value is not nil.
func (iu *ItemUpdate) SetNillableCat(s *string) *ItemUpdate {
	if s != nil {
		iu.SetCat(*s)
	}
	return iu
}

// SetSize sets the "size" field.
func (iu *ItemUpdate) SetSize(i int) *ItemUpdate {
	iu.mutation.ResetSize()
	iu.mutation.SetSize(i)
	return iu
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (iu *ItemUpdate) SetNillableSize(i *int) *ItemUpdate {
	if i != nil {
		iu.SetSize(*i)
	}
	return iu
}

// AddSize adds i to the "size" field.
func (iu *ItemUpdate) AddSize(i int) *ItemUpdate {
	iu.mutation.AddSize(i)
	return iu
}

// SetExtID sets the "ext_id" field.
func (iu *ItemUpdate) SetExtID(s string) *ItemUpdate {
	iu.mutation.SetExtID(s)
	return iu
}

// SetNillableExtID sets the "ext_id" field if the given value is not nil.
func (iu *ItemUpdate) SetNillableExtID(s *string) *ItemUpdate {
	if s != nil {
		iu.SetExtID(*s)
	}
	return iu
}

// ClearExtID clears the value of the "ext_id" field.
func (iu *ItemUpdate) ClearExtID() *ItemUpdate {
	iu.mutation.ClearExtID()
	return iu
}

// SetImdb sets the "imdb" field.
func (iu *ItemUpdate) SetImdb(s string) *ItemUpdate {
	iu.mutation.SetImdb(s)
	return iu
}

// SetNillableImdb sets the "imdb" field if the given value is not nil.
func (iu *ItemUpdate) SetNillableImdb(s *string) *ItemUpdate {
	if s != nil {
		iu.SetImdb(*s)
	}
	return iu
}

// ClearImdb clears the value of the "imdb" field.
func (iu *ItemUpdate) ClearImdb() *ItemUpdate {
	iu.mutation.ClearImdb()
	return iu
}

// Mutation returns the ItemMutation object of the builder.
func (iu *ItemUpdate) Mutation() *ItemMutation {
	return iu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iu *ItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, iu.sqlSave, iu.mutation, iu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iu *ItemUpdate) SaveX(ctx context.Context) int {
	affected, err := iu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iu *ItemUpdate) Exec(ctx context.Context) error {
	_, err := iu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iu *ItemUpdate) ExecX(ctx context.Context) {
	if err := iu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (iu *ItemUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(item.Table, item.Columns, sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt))
	if ps := iu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iu.mutation.Hash(); ok {
		_spec.SetField(item.FieldHash, field.TypeString, value)
	}
	if value, ok := iu.mutation.Title(); ok {
		_spec.SetField(item.FieldTitle, field.TypeString, value)
	}
	if value, ok := iu.mutation.Dt(); ok {
		_spec.SetField(item.FieldDt, field.TypeString, value)
	}
	if value, ok := iu.mutation.Cat(); ok {
		_spec.SetField(item.FieldCat, field.TypeString, value)
	}
	if value, ok := iu.mutation.Size(); ok {
		_spec.SetField(item.FieldSize, field.TypeInt, value)
	}
	if value, ok := iu.mutation.AddedSize(); ok {
		_spec.AddField(item.FieldSize, field.TypeInt, value)
	}
	if value, ok := iu.mutation.ExtID(); ok {
		_spec.SetField(item.FieldExtID, field.TypeString, value)
	}
	if iu.mutation.ExtIDCleared() {
		_spec.ClearField(item.FieldExtID, field.TypeString)
	}
	if value, ok := iu.mutation.Imdb(); ok {
		_spec.SetField(item.FieldImdb, field.TypeString, value)
	}
	if iu.mutation.ImdbCleared() {
		_spec.ClearField(item.FieldImdb, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{item.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	iu.mutation.done = true
	return n, nil
}

// ItemUpdateOne is the builder for updating a single Item entity.
type ItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ItemMutation
}

// SetHash sets the "hash" field.
func (iuo *ItemUpdateOne) SetHash(s string) *ItemUpdateOne {
	iuo.mutation.SetHash(s)
	return iuo
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (iuo *ItemUpdateOne) SetNillableHash(s *string) *ItemUpdateOne {
	if s != nil {
		iuo.SetHash(*s)
	}
	return iuo
}

// SetTitle sets the "title" field.
func (iuo *ItemUpdateOne) SetTitle(s string) *ItemUpdateOne {
	iuo.mutation.SetTitle(s)
	return iuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (iuo *ItemUpdateOne) SetNillableTitle(s *string) *ItemUpdateOne {
	if s != nil {
		iuo.SetTitle(*s)
	}
	return iuo
}

// SetDt sets the "dt" field.
func (iuo *ItemUpdateOne) SetDt(s string) *ItemUpdateOne {
	iuo.mutation.SetDt(s)
	return iuo
}

// SetNillableDt sets the "dt" field if the given value is not nil.
func (iuo *ItemUpdateOne) SetNillableDt(s *string) *ItemUpdateOne {
	if s != nil {
		iuo.SetDt(*s)
	}
	return iuo
}

// SetCat sets the "cat" field.
func (iuo *ItemUpdateOne) SetCat(s string) *ItemUpdateOne {
	iuo.mutation.SetCat(s)
	return iuo
}

// SetNillableCat sets the "cat" field if the given value is not nil.
func (iuo *ItemUpdateOne) SetNillableCat(s *string) *ItemUpdateOne {
	if s != nil {
		iuo.SetCat(*s)
	}
	return iuo
}

// SetSize sets the "size" field.
func (iuo *ItemUpdateOne) SetSize(i int) *ItemUpdateOne {
	iuo.mutation.ResetSize()
	iuo.mutation.SetSize(i)
	return iuo
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (iuo *ItemUpdateOne) SetNillableSize(i *int) *ItemUpdateOne {
	if i != nil {
		iuo.SetSize(*i)
	}
	return iuo
}

// AddSize adds i to the "size" field.
func (iuo *ItemUpdateOne) AddSize(i int) *ItemUpdateOne {
	iuo.mutation.AddSize(i)
	return iuo
}

// SetExtID sets the "ext_id" field.
func (iuo *ItemUpdateOne) SetExtID(s string) *ItemUpdateOne {
	iuo.mutation.SetExtID(s)
	return iuo
}

// SetNillableExtID sets the "ext_id" field if the given value is not nil.
func (iuo *ItemUpdateOne) SetNillableExtID(s *string) *ItemUpdateOne {
	if s != nil {
		iuo.SetExtID(*s)
	}
	return iuo
}

// ClearExtID clears the value of the "ext_id" field.
func (iuo *ItemUpdateOne) ClearExtID() *ItemUpdateOne {
	iuo.mutation.ClearExtID()
	return iuo
}

// SetImdb sets the "imdb" field.
func (iuo *ItemUpdateOne) SetImdb(s string) *ItemUpdateOne {
	iuo.mutation.SetImdb(s)
	return iuo
}

// SetNillableImdb sets the "imdb" field if the given value is not nil.
func (iuo *ItemUpdateOne) SetNillableImdb(s *string) *ItemUpdateOne {
	if s != nil {
		iuo.SetImdb(*s)
	}
	return iuo
}

// ClearImdb clears the value of the "imdb" field.
func (iuo *ItemUpdateOne) ClearImdb() *ItemUpdateOne {
	iuo.mutation.ClearImdb()
	return iuo
}

// Mutation returns the ItemMutation object of the builder.
func (iuo *ItemUpdateOne) Mutation() *ItemMutation {
	return iuo.mutation
}

// Where appends a list predicates to the ItemUpdate builder.
func (iuo *ItemUpdateOne) Where(ps ...predicate.Item) *ItemUpdateOne {
	iuo.mutation.Where(ps...)
	return iuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iuo *ItemUpdateOne) Select(field string, fields ...string) *ItemUpdateOne {
	iuo.fields = append([]string{field}, fields...)
	return iuo
}

// Save executes the query and returns the updated Item entity.
func (iuo *ItemUpdateOne) Save(ctx context.Context) (*Item, error) {
	return withHooks(ctx, iuo.sqlSave, iuo.mutation, iuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iuo *ItemUpdateOne) SaveX(ctx context.Context) *Item {
	node, err := iuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iuo *ItemUpdateOne) Exec(ctx context.Context) error {
	_, err := iuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iuo *ItemUpdateOne) ExecX(ctx context.Context) {
	if err := iuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (iuo *ItemUpdateOne) sqlSave(ctx context.Context) (_node *Item, err error) {
	_spec := sqlgraph.NewUpdateSpec(item.Table, item.Columns, sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt))
	id, ok := iuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Item.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, item.FieldID)
		for _, f := range fields {
			if !item.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != item.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iuo.mutation.Hash(); ok {
		_spec.SetField(item.FieldHash, field.TypeString, value)
	}
	if value, ok := iuo.mutation.Title(); ok {
		_spec.SetField(item.FieldTitle, field.TypeString, value)
	}
	if value, ok := iuo.mutation.Dt(); ok {
		_spec.SetField(item.FieldDt, field.TypeString, value)
	}
	if value, ok := iuo.mutation.Cat(); ok {
		_spec.SetField(item.FieldCat, field.TypeString, value)
	}
	if value, ok := iuo.mutation.Size(); ok {
		_spec.SetField(item.FieldSize, field.TypeInt, value)
	}
	if value, ok := iuo.mutation.AddedSize(); ok {
		_spec.AddField(item.FieldSize, field.TypeInt, value)
	}
	if value, ok := iuo.mutation.ExtID(); ok {
		_spec.SetField(item.FieldExtID, field.TypeString, value)
	}
	if iuo.mutation.ExtIDCleared() {
		_spec.ClearField(item.FieldExtID, field.TypeString)
	}
	if value, ok := iuo.mutation.Imdb(); ok {
		_spec.SetField(item.FieldImdb, field.TypeString, value)
	}
	if iuo.mutation.ImdbCleared() {
		_spec.ClearField(item.FieldImdb, field.TypeString)
	}
	_node = &Item{config: iuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{item.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	iuo.mutation.done = true
	return _node, nil
}
